import sys
from PyQt6.QtWidgets import (QApplication, QMainWindow, QLabel, QPushButton, QWidget, QVBoxLayout, QStatusBar)
class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("PlakOn Professional")
        self.resize(800,500)
        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        self.label = QLabel("سیستم آماده است")
        self.button = QPushButton("شروع پردازش...")
        self.button.clicked.connect(self.on_click)
        layout = QVBoxLayout()
        layout.addWidget(self.label)
        layout.addWidget(self.button)
        central_widget.setLayout(layout)
        self.setStatusBar(QStatusBar(self))
        self.statusBar().showMessage("آماده!")
    def on_click(self):
        self.label.setText("درحال پردازش پلاک...")
        self.statusBar().showMessage("پردازش شروع شد")
app = QApplication(sys.argv)
window = MainWindow()
window.show()
sys.exit(app.exec())         